name: Deploy Blog
on:
  push:
    branches: [main]
jobs:
  deploy-blog:
    name: Deploy @product/blog
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: prj_xLpsnf8Zm4pfSaRHqdVPfJeO4Vid
          vercel-args: '--prod'
